/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e5e2e1',
        'inverse-on-surface': '#f3f0ef',
        outline: '#737685',
        'on-surface-variant': '#434654',
        'surface-container-highest': '#e5e2e1',
        'tertiary-fixed': '#c9e7f7',
        'primary-fixed-dim': '#b2c5ff',
        'tertiary-container': '#425f6c',
        'surface-dim': '#dcd9d9',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#001f2a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#adcbda',
        'secondary-container': '#d7e4ec',
        'outline-variant': '#c3c6d6',
        'on-primary-fixed': '#001848',
        secondary: '#546067',
        'on-secondary-fixed': '#111d23',
        'primary-container': '#0052cc',
        'on-secondary-fixed-variant': '#3c494f',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-bright': '#fcf9f8',
        primary: '#003d9b',
        primaryDark: '#00337f',
        surface: '#fcf9f8',
        'surface-tint': '#0c56d0',
        'surface-container-low': '#f6f3f2',
        'inverse-surface': '#313030',
        'surface-container': '#f0edec',
        'on-surface': '#1c1b1b',
        'on-error': '#ffffff',
        'on-primary-container': '#c4d2ff',
        'inverse-primary': '#b2c5ff',
        background: '#fcf9f8',
        'secondary-fixed-dim': '#bbc8d0',
        'secondary-fixed': '#d7e4ec',
        'on-background': '#1c1b1b',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#0040a2',
        'on-tertiary-fixed-variant': '#2e4b57',
        'surface-container-high': '#ebe7e7',
        'primary-fixed': '#dae2ff',
        error: '#ba1a1a',
        'on-tertiary-container': '#b9d8e7',
        'on-secondary-container': '#5a666d',
        tertiary: '#2a4754',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        soft: '0px 20px 40px rgba(28,27,27,0.06)',
      },
    },
  },
  plugins: [],
}
